"""link staff patients to users

Revision ID: 1c311bce95f8
Revises: 185c0c9002bb
Create Date: 2026-01-24 15:24:10.073619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1c311bce95f8'
down_revision: Union[str, Sequence[str], None] = '185c0c9002bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workers_user_id'), 'workers', ['user_id'], unique=True)
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_user_id'), table_name='workers')
    op.drop_column('workers', 'user_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_column('patients', 'user_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_column('doctors', 'user_id')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B616F4B1AB3'))
    )
    # ### end Alembic commands ###
